export const FakeData = [
  {
    id: 1,
    accountName: "Rajan Dubey",
    accountCode: "AC001",
    city: "Mumbai",
    address: "Andheri East",
    companyName: "TechNova Pvt Ltd",
    email: "rajan@technova.com",
    mobile: "9876543210",
    website: "www.technova.com",
    mfgCode: "MFG001",
    state: "Maharashtra",
    group: "Electronics",
    country: "India",
    logo: null,
    type: "Yes",
  },
  {
    id: 2,
    accountName: "Neha Sharma",
    accountCode: "AC002",
    city: "Delhi",
    address: "Connaught Place",
    companyName: "CodeMatrix Ltd",
    email: "neha@codematrix.com",
    mobile: "9988776655",
    website: "www.codematrix.com",
    mfgCode: "MFG002",
    state: "Delhi",
    group: "Software",
    country: "India",
    logo: null,
    type: "No",
  },
  {
    id: 3,
    accountName: "Amit Patel",
    accountCode: "AC003",
    city: "Ahmedabad",
    address: "Satellite",
    companyName: "GreenTech Systems",
    email: "amit@greentech.in",
    mobile: "9723456789",
    website: "www.greentech.in",
    mfgCode: "MFG003",
    state: "Gujarat",
    group: "Renewable Energy",
    country: "India",
    logo: null,
    type: "Yes",
  },
  {
    id: 4,
    accountName: "Priya Mehta",
    accountCode: "AC004",
    city: "Bangalore",
    address: "Whitefield",
    companyName: "SkyNet Solutions",
    email: "priya@skynet.com",
    mobile: "9123456789",
    website: "www.skynet.com",
    mfgCode: "MFG004",
    state: "Karnataka",
    group: "IT Services",
    country: "India",
    logo: null,
    type: "No",
  },
  {
    id: 5,
    accountName: "Rohit Verma",
    accountCode: "AC005",
    city: "Pune",
    address: "Kothrud",
    companyName: "NextGen Robotics",
    email: "rohit@nextgen.com",
    mobile: "9822113344",
    website: "www.nextgen.com",
    mfgCode: "MFG005",
    state: "Maharashtra",
    group: "Automation",
    country: "India",
    logo: null,
    type: "Yes",
  },
];

export const salesData = [
  { name: "Electronics", value: 400 },
  { name: "Fashion", value: 300 },
  { name: "Groceries", value: 300 },
  { name: "Furniture", value: 200 },
  { name: "Toys", value: 150 },
];

export const FakeCustomerData = [
  {
    id: 1,
    customerName: "Tata Steel Ltd.",
    contactPerson: "Rohit Sharma",
    email: "rohit.sharma@tatasteel.com",
    contactNo: "022-22334455",
    customerCode: "CUST001",
    designation: "Purchase Manager",
    mobileNo: "9876543210",
    fat: "5%",
    city: "Mumbai",
    pincode: "400020",
    tinNo: "TIN123456",
    panNo: "ABCDE1234F",
    cstNo: "CST654321",
    gstNo: "27ABCDE1234F1Z5",
    creditLimit: "₹10,00,000",
    creditDays: "30",
    sourceEmployee: "Amit Verma",
    exciseNo: "EXC12345",
    annualTurnover: "₹50 Cr",
    country: "India",
    state: "Maharashtra",
    customerType: "Corporate",
    activeStatus: true,
    gstExempt: false,
  },
  {
    id: 2,
    customerName: "Reliance Retail",
    contactPerson: "Anita Verma",
    email: "anita.verma@relianceretail.com",
    contactNo: "011-44556677",
    customerCode: "CUST002",
    designation: "Branch Manager",
    mobileNo: "9998877665",
    fat: "3%",
    city: "New Delhi",
    pincode: "110001",
    tinNo: "TIN654321",
    panNo: "PQRSX9876T",
    cstNo: "CST789654",
    gstNo: "07PQRSX9876T1Z2",
    creditLimit: "₹5,00,000",
    creditDays: "45",
    sourceEmployee: "Suman Joshi",
    exciseNo: "EXC56789",
    annualTurnover: "₹25 Cr",
    country: "India",
    state: "Delhi",
    customerType: "Wholesale",
    activeStatus: true,
    gstExempt: false,
  },
  {
    id: 3,
    customerName: "Big Bazaar",
    contactPerson: "Vikas Gupta",
    email: "vikas.gupta@bigbazaar.com",
    contactNo: "0522-4455667",
    customerCode: "CUST003",
    designation: "Sales Executive",
    mobileNo: "9988776655",
    fat: "2%",
    city: "Lucknow",
    pincode: "226001",
    tinNo: "TIN789456",
    panNo: "LMNOP4567Q",
    cstNo: "CST321654",
    gstNo: "09LMNOP4567Q1Z3",
    creditLimit: "₹2,00,000",
    creditDays: "15",
    sourceEmployee: "Ritu Singh",
    exciseNo: "EXC78912",
    annualTurnover: "₹8 Cr",
    country: "India",
    state: "Uttar Pradesh",
    customerType: "Retail",
    activeStatus: true,
    gstExempt: false,
  },
  {
    id: 4,
    customerName: "Walmart Inc.",
    contactPerson: "John Carter",
    email: "john.carter@walmart.com",
    contactNo: "+1 212-334-5566",
    customerCode: "CUST004",
    designation: "Procurement Lead",
    mobileNo: "+1 9876543210",
    fat: "7%",
    city: "New York",
    pincode: "10005",
    tinNo: "TINNY5432",
    panNo: "USPAN1234Y",
    cstNo: "CSTNY8765",
    gstNo: "USGST87654",
    creditLimit: "₹50,00,000",
    creditDays: "60",
    sourceEmployee: "Neha Rao",
    exciseNo: "EXC99876",
    annualTurnover: "₹100 Cr",
    country: "USA",
    state: "New York",
    customerType: "Corporate",
    activeStatus: true,
    gstExempt: true,
  },
  {
    id: 5,
    customerName: "Tesco PLC",
    contactPerson: "Emma Watson",
    email: "emma.watson@tesco.com",
    contactNo: "+44 20 7946 0958",
    customerCode: "CUST005",
    designation: "Finance Head",
    mobileNo: "+44 7894561230",
    fat: "6%",
    city: "London",
    pincode: "NW16XE",
    tinNo: "TIN12345",
    panNo: "ABCDE9999Z",
    cstNo: "CST56789",
    gstNo: "UKG9876543",
    creditLimit: "₹20,00,000",
    creditDays: "30",
    sourceEmployee: "Manish Mehta",
    exciseNo: "EXC11111",
    annualTurnover: "₹60 Cr",
    country: "UK",
    state: "Greater London",
    customerType: "Corporate",
    activeStatus: false,
    gstExempt: false,
  },
];




export const FakeBranchData = [
  {
    id: 1,
    branchName: "Mumbai HQ",
    contactPerson: "Rohit Sharma",
    email: "rohit.sharma@company.com",
    designation: "Branch Manager",
    mobileNo: "9876543210",
    address: "123 Marine Drive, Churchgate",
    fax: "022-22334455",
    contactNo: "022-99887766",
    pincode: "400020",
    cstNo: "CST12345",
    tinNo: "TIN56789",
    panNo: "ABCDE1234F",
    gstNo: "27ABCDE1234F1Z5",
    annualTurnover: "5 Cr",
    city: "Mumbai",
    country: "India",
    state: "Maharashtra",
  },
  {
    id: 2,
    branchName: "Delhi Branch",
    contactPerson: "Anita Verma",
    email: "anita.verma@company.com",
    designation: "Regional Head",
    mobileNo: "9998877665",
    address: "A-45 Connaught Place",
    fax: "011-33445566",
    contactNo: "011-99887744",
    pincode: "110001",
    cstNo: "CST54321",
    tinNo: "TIN98765",
    panNo: "PQRSX9876T",
    gstNo: "07PQRSX9876T1Z2",
    annualTurnover: "3 Cr",
    city: "New Delhi",
    country: "India",
    state: "Delhi",
  },
  {
    id: 3,
    branchName: "Lucknow Office",
    contactPerson: "Vikas Gupta",
    email: "vikas.gupta@company.com",
    designation: "Sales Executive",
    mobileNo: "9988776655",
    address: "45 Hazratganj Market",
    fax: "0522-2233445",
    contactNo: "0522-4455667",
    pincode: "226001",
    cstNo: "CST99887",
    tinNo: "TIN65432",
    panNo: "LMNOP4567Q",
    gstNo: "09LMNOP4567Q1Z3",
    annualTurnover: "1.2 Cr",
    city: "Lucknow",
    country: "India",
    state: "Uttar Pradesh",
  },
  {
    id: 4,
    branchName: "London Office",
    contactPerson: "John Carter",
    email: "john.carter@company.com",
    designation: "Operations Head",
    mobileNo: "+44 7894561230",
    address: "221B Baker Street",
    fax: "+44 20 7946 0958",
    contactNo: "+44 20 1234 5678",
    pincode: "NW16XE",
    cstNo: "CST56789",
    tinNo: "TIN12345",
    panNo: "ABCDE9999Z",
    gstNo: "UKG9876543",
    annualTurnover: "10 Cr",
    city: "London",
    country: "UK",
    state: "Greater London",
  },
];

export const FakeFollowUpActivityData = [
  {
    id: 1,
    dueDateTime: "2025-11-05T10:30",
    reminderDateTime: "2025-11-04T09:00",
    remarks: "Follow up with client about proposal status.",
    followUpStatusReason: "Client requested more time to decide.",
    assignFollowUp: "John Doe",
    followUpActivity: "Call Client",
    followUpActivityType: "Telephonic",
    priority: "High",
    followUpStatus: "Pending",
  },
  {
    id: 2,
    dueDateTime: "2025-11-08T15:00",
    reminderDateTime: "2025-11-07T12:00",
    remarks: "Send updated quotation and confirm meeting.",
    followUpStatusReason: "Quotation update required",
    assignFollowUp: "Priya Sharma",
    followUpActivity: "Send Email",
    followUpActivityType: "Email",
    priority: "Medium",
    followUpStatus: "In Progress",
  },
  {
    id: 3,
    dueDateTime: "2025-11-10T11:00",
    reminderDateTime: "2025-11-09T09:00",
    remarks: "Schedule follow-up demo for software feature.",
    followUpStatusReason: "Demo postponed by client",
    assignFollowUp: "Ravi Kumar",
    followUpActivity: "Product Demo",
    followUpActivityType: "Meeting",
    priority: "High",
    followUpStatus: "Scheduled",
  },
  {
    id: 4,
    dueDateTime: "2025-11-12T16:30",
    reminderDateTime: "2025-11-11T15:00",
    remarks: "Check in after delivery for feedback.",
    followUpStatusReason: "Awaiting delivery confirmation",
    assignFollowUp: "Anjali Singh",
    followUpActivity: "Feedback Call",
    followUpActivityType: "Phone",
    priority: "Low",
    followUpStatus: "Completed",
  },
];

export const FakeInterestedProductData = [
   {
    id: 1,
    productName: "Steel Rod 10mm",
    productCode: "SR-10",
    productShortDesc: "High tensile steel rod",
  },
  {
    id: 2,
    productName: "PVC Pipe 1 inch",
    productCode: "PVC-01",
    productShortDesc: "1 inch water pipe",
  },
  {
    id: 3,
    productName: "Hydraulic Pump",
    productCode: "HP-250",
    productShortDesc: "Industrial hydraulic pump",
  },
  {
    id: 4,
    productName: "Lubricant Oil 1L",
    productCode: "LO-1L",
    productShortDesc: "Engine lubricant oil",
  },
  {
    id: 5,
    productName: "Copper Wire Roll",
    productCode: "CW-50",
    productShortDesc: "50m copper wire roll",
  },
];

export const fakeMainProductData = [
  {
    id: 1,
    productName: "Wireless Mouse",
    productCode: "PRD001",
    size: "Medium",
    length: "12 cm",
    manufacturedBrand: "Logitech",
    hsnCode: "84716060",
    salePrice: 899,
    purchasePrice: 700,
    reorderQty: 20,
    minOrderQty: 5,
    cgst: 9,
    sgst: 9,
    igst: 18,
    productType: "Finished",
    productMainGroup: "Electronics",
    productSubGroup: "Computer Accessories",
    assemblyType: "Automatic",
    saleUom: "Piece",
    purchaseUom: "Piece",
    serialApplicable: false,
    gstExempt: false,
    activeStatus: true,
    productImage: "mouse.jpg",
  },
  {
    id: 2,
    productName: "Office Chair",
    productCode: "PRD002",
    size: "Large",
    length: "100 cm",
    manufacturedBrand: "Godrej",
    hsnCode: "94013000",
    salePrice: 3200,
    purchasePrice: 2500,
    reorderQty: 10,
    minOrderQty: 2,
    cgst: 9,
    sgst: 9,
    igst: 18,
    productType: "Finished",
    productMainGroup: "Furniture",
    productSubGroup: "Office",
    assemblyType: "Manual",
    saleUom: "Piece",
    purchaseUom: "Piece",
    serialApplicable: false,
    gstExempt: false,
    activeStatus: true,
    productImage: "chair.jpg",
  },
  {
    id: 3,
    productName: "Bluetooth Headphones",
    productCode: "PRD003",
    size: "Standard",
    length: "18 cm",
    manufacturedBrand: "Boat",
    hsnCode: "85183000",
    salePrice: 1599,
    purchasePrice: 1200,
    reorderQty: 25,
    minOrderQty: 5,
    cgst: 9,
    sgst: 9,
    igst: 18,
    productType: "Finished",
    productMainGroup: "Electronics",
    productSubGroup: "Audio",
    assemblyType: "Automatic",
    saleUom: "Piece",
    purchaseUom: "Piece",
    serialApplicable: true,
    gstExempt: false,
    activeStatus: true,
    productImage: "headphones.jpg",
  },
  {
    id: 4,
    productName: "Wooden Table",
    productCode: "PRD004",
    size: "Large",
    length: "150 cm",
    manufacturedBrand: "Durian",
    hsnCode: "94036000",
    salePrice: 5499,
    purchasePrice: 4200,
    reorderQty: 8,
    minOrderQty: 2,
    cgst: 9,
    sgst: 9,
    igst: 18,
    productType: "Finished",
    productMainGroup: "Furniture",
    productSubGroup: "Home",
    assemblyType: "Manual",
    saleUom: "Piece",
    purchaseUom: "Piece",
    serialApplicable: false,
    gstExempt: false,
    activeStatus: true,
    productImage: "table.jpg",
  },
  {
    id: 5,
    productName: "Smart Watch",
    productCode: "PRD005",
    size: "Small",
    length: "5 cm",
    manufacturedBrand: "Noise",
    hsnCode: "85176290",
    salePrice: 2499,
    purchasePrice: 2000,
    reorderQty: 30,
    minOrderQty: 10,
    cgst: 9,
    sgst: 9,
    igst: 18,
    productType: "Finished",
    productMainGroup: "Electronics",
    productSubGroup: "Wearables",
    assemblyType: "Automatic",
    saleUom: "Piece",
    purchaseUom: "Piece",
    serialApplicable: true,
    gstExempt: false,
    activeStatus: true,
    productImage: "smartwatch.jpg",
  },
  {
    id: 6,
    productName: "Leather Wallet",
    productCode: "PRD006",
    size: "Small",
    length: "9 cm",
    manufacturedBrand: "WildHorn",
    hsnCode: "42023120",
    salePrice: 899,
    purchasePrice: 600,
    reorderQty: 40,
    minOrderQty: 10,
    cgst: 9,
    sgst: 9,
    igst: 18,
    productType: "Finished",
    productMainGroup: "Accessories",
    productSubGroup: "Leather",
    assemblyType: "Manual",
    saleUom: "Piece",
    purchaseUom: "Piece",
    serialApplicable: false,
    gstExempt: false,
    activeStatus: true,
    productImage: "wallet.jpg",
  },
  {
    id: 7,
    productName: "Electric Kettle",
    productCode: "PRD007",
    size: "Standard",
    length: "22 cm",
    manufacturedBrand: "Philips",
    hsnCode: "85167920",
    salePrice: 1899,
    purchasePrice: 1500,
    reorderQty: 20,
    minOrderQty: 5,
    cgst: 9,
    sgst: 9,
    igst: 18,
    productType: "Finished",
    productMainGroup: "Appliances",
    productSubGroup: "Kitchen",
    assemblyType: "Automatic",
    saleUom: "Piece",
    purchaseUom: "Piece",
    serialApplicable: true,
    gstExempt: false,
    activeStatus: true,
    productImage: "kettle.jpg",
  },
  {
    id: 8,
    productName: "Running Shoes",
    productCode: "PRD008",
    size: "9 UK",
    length: "28 cm",
    manufacturedBrand: "Puma",
    hsnCode: "64041190",
    salePrice: 2999,
    purchasePrice: 2400,
    reorderQty: 25,
    minOrderQty: 5,
    cgst: 9,
    sgst: 9,
    igst: 18,
    productType: "Finished",
    productMainGroup: "Footwear",
    productSubGroup: "Sports",
    assemblyType: "Manual",
    saleUom: "Pair",
    purchaseUom: "Pair",
    serialApplicable: false,
    gstExempt: false,
    activeStatus: true,
    productImage: "shoes.jpg",
  },
  {
    id: 9,
    productName: "Desk Organizer",
    productCode: "PRD009",
    size: "Medium",
    length: "25 cm",
    manufacturedBrand: "Cello",
    hsnCode: "39261019",
    salePrice: 699,
    purchasePrice: 500,
    reorderQty: 50,
    minOrderQty: 10,
    cgst: 9,
    sgst: 9,
    igst: 18,
    productType: "Finished",
    productMainGroup: "Office Supplies",
    productSubGroup: "Organizers",
    assemblyType: "Manual",
    saleUom: "Piece",
    purchaseUom: "Piece",
    serialApplicable: false,
    gstExempt: false,
    activeStatus: true,
    productImage: "organizer.jpg",
  },
  {
    id: 10,
    productName: "Power Bank",
    productCode: "PRD010",
    size: "Small",
    length: "15 cm",
    manufacturedBrand: "Mi",
    hsnCode: "85076000",
    salePrice: 1499,
    purchasePrice: 1100,
    reorderQty: 30,
    minOrderQty: 10,
    cgst: 9,
    sgst: 9,
    igst: 18,
    productType: "Finished",
    productMainGroup: "Electronics",
    productSubGroup: "Power",
    assemblyType: "Automatic",
    saleUom: "Piece",
    purchaseUom: "Piece",
    serialApplicable: true,
    gstExempt: false,
    activeStatus: true,
    productImage: "powerbank.jpg",
  },
  {
    id: 11,
    productName: "Microwave Oven",
    productCode: "PRD011",
    size: "Standard",
    length: "45 cm",
    manufacturedBrand: "Samsung",
    hsnCode: "85165000",
    salePrice: 8499,
    purchasePrice: 7000,
    reorderQty: 10,
    minOrderQty: 2,
    cgst: 9,
    sgst: 9,
    igst: 18,
    productType: "Finished",
    productMainGroup: "Appliances",
    productSubGroup: "Kitchen",
    assemblyType: "Automatic",
    saleUom: "Piece",
    purchaseUom: "Piece",
    serialApplicable: true,
    gstExempt: false,
    activeStatus: true,
    productImage: "microwave.jpg",
  },
  {
    id: 12,
    productName: "Table Lamp",
    productCode: "PRD012",
    size: "Medium",
    length: "35 cm",
    manufacturedBrand: "Wipro",
    hsnCode: "94052010",
    salePrice: 1299,
    purchasePrice: 1000,
    reorderQty: 25,
    minOrderQty: 5,
    cgst: 9,
    sgst: 9,
    igst: 18,
    productType: "Finished",
    productMainGroup: "Home Decor",
    productSubGroup: "Lighting",
    assemblyType: "Manual",
    saleUom: "Piece",
    purchaseUom: "Piece",
    serialApplicable: false,
    gstExempt: false,
    activeStatus: true,
    productImage: "lamp.jpg",
  },
  {
    id: 13,
    productName: "Laptop Stand",
    productCode: "PRD013",
    size: "Adjustable",
    length: "28 cm",
    manufacturedBrand: "Portronics",
    hsnCode: "76169990",
    salePrice: 1599,
    purchasePrice: 1200,
    reorderQty: 30,
    minOrderQty: 5,
    cgst: 9,
    sgst: 9,
    igst: 18,
    productType: "Finished",
    productMainGroup: "Accessories",
    productSubGroup: "Office",
    assemblyType: "Manual",
    saleUom: "Piece",
    purchaseUom: "Piece",
    serialApplicable: false,
    gstExempt: false,
    activeStatus: true,
    productImage: "laptopstand.jpg",
  },
  {
    id: 14,
    productName: "Backpack",
    productCode: "PRD014",
    size: "Large",
    length: "50 cm",
    manufacturedBrand: "American Tourister",
    hsnCode: "42029200",
    salePrice: 1999,
    purchasePrice: 1500,
    reorderQty: 40,
    minOrderQty: 10,
    cgst: 9,
    sgst: 9,
    igst: 18,
    productType: "Finished",
    productMainGroup: "Accessories",
    productSubGroup: "Bags",
    assemblyType: "Manual",
    saleUom: "Piece",
    purchaseUom: "Piece",
    serialApplicable: false,
    gstExempt: false,
    activeStatus: true,
    productImage: "backpack.jpg",
  },
  {
    id: 15,
    productName: "Sunglasses",
    productCode: "PRD015",
    size: "Standard",
    length: "14 cm",
    manufacturedBrand: "RayBan",
    hsnCode: "90041000",
    salePrice: 2499,
    purchasePrice: 1800,
    reorderQty: 20,
    minOrderQty: 5,
    cgst: 9,
    sgst: 9,
    igst: 18,
    productType: "Finished",
    productMainGroup: "Accessories",
    productSubGroup: "Eyewear",
    assemblyType: "Manual",
    saleUom: "Piece",
    purchaseUom: "Piece",
    serialApplicable: false,
    gstExempt: false,
    activeStatus: true,
    productImage: "sunglasses.jpg",
  },
  {
    id: 16,
    productName: "Cookware Set",
    productCode: "PRD016",
    size: "Standard",
    length: "40 cm",
    manufacturedBrand: "Prestige",
    hsnCode: "73239390",
    salePrice: 4999,
    purchasePrice: 3800,
    reorderQty: 10,
    minOrderQty: 2,
    cgst: 9,
    sgst: 9,
    igst: 18,
    productType: "Finished",
    productMainGroup: "Home & Kitchen",
    productSubGroup: "Cookware",
    assemblyType: "Manual",
    saleUom: "Set",
    purchaseUom: "Set",
    serialApplicable: false,
    gstExempt: false,
    activeStatus: true,
    productImage: "cookware.jpg",
  },
  {
    id: 17,
    productName: "Gym Bottle",
    productCode: "PRD017",
    size: "1 Litre",
    length: "28 cm",
    manufacturedBrand: "Milton",
    hsnCode: "39233090",
    salePrice: 699,
    purchasePrice: 500,
    reorderQty: 50,
    minOrderQty: 10,
    cgst: 9,
    sgst: 9,
    igst: 18,
    productType: "Finished",
    productMainGroup: "Fitness",
    productSubGroup: "Accessories",
    assemblyType: "Automatic",
    saleUom: "Piece",
    purchaseUom: "Piece",
    serialApplicable: false,
    gstExempt: false,
    activeStatus: true,
    productImage: "bottle.jpg",
  },
  {
    id: 18,
    productName: "Ceiling Fan",
    productCode: "PRD018",
    size: "1200 mm",
    length: "60 cm",
    manufacturedBrand: "Havells",
    hsnCode: "84145120",
    salePrice: 2399,
    purchasePrice: 1900,
    reorderQty: 15,
    minOrderQty: 3,
    cgst: 9,
    sgst: 9,
    igst: 18,
    productType: "Finished",
    productMainGroup: "Appliances",
    productSubGroup: "Electrical",
    assemblyType: "Automatic",
    saleUom: "Piece",
    purchaseUom: "Piece",
    serialApplicable: true,
    gstExempt: false,
    activeStatus: true,
    productImage: "fan.jpg",
  },
  {
    id: 19,
    productName: "Air Purifier",
    productCode: "PRD019",
    size: "Compact",
    length: "40 cm",
    manufacturedBrand: "Dyson",
    hsnCode: "84213920",
    salePrice: 15999,
    purchasePrice: 13000,
    reorderQty: 5,
    minOrderQty: 1,
    cgst: 9,
    sgst: 9,
    igst: 18,
    productType: "Finished",
    productMainGroup: "Appliances",
    productSubGroup: "Home",
    assemblyType: "Automatic",
    saleUom: "Piece",
    purchaseUom: "Piece",
    serialApplicable: true,
    gstExempt: false,
    activeStatus: true,
    productImage: "airpurifier.jpg",
  },
  {
    id: 20,
    productName: "Bluetooth Speaker",
    productCode: "PRD020",
    size: "Small",
    length: "18 cm",
    manufacturedBrand: "JBL",
    hsnCode: "85182200",
    salePrice: 2499,
    purchasePrice: 2000,
    reorderQty: 25,
    minOrderQty: 5,
    cgst: 9,
    sgst: 9,
    igst: 18,
    productType: "Finished",
    productMainGroup: "Electronics",
    productSubGroup: "Audio",
    assemblyType: "Automatic",
    saleUom: "Piece",
    purchaseUom: "Piece",
    serialApplicable: true,
    gstExempt: false,
    activeStatus: true,
    productImage: "speaker.jpg",
  },
];

export const FakeGroupData = [
  { id: 1, groupName: "North Region Dealers", remark: "Handles all northern area clients", activeStatus: true },
  { id: 2, groupName: "South Zone Distributors", remark: "Focuses on southern distributors", activeStatus: false },
  { id: 3, groupName: "Premium Clients", remark: "Top-tier loyal customers", activeStatus: true },
  { id: 4, groupName: "Corporate Accounts", remark: "Large-scale B2B clients", activeStatus: true },
  { id: 5, groupName: "Retail Partners", remark: "Local store and franchise groups", activeStatus: false },
  { id: 6, groupName: "International Clients", remark: "Customers from overseas markets", activeStatus: true },
  { id: 7, groupName: "Online Vendors", remark: "Partners operating via e-commerce", activeStatus: true },
  { id: 8, groupName: "Seasonal Buyers", remark: "Active during festive and seasonal sales", activeStatus: false },
  { id: 9, groupName: "Testing Group", remark: "Used for internal QA and demo purposes", activeStatus: true },
  { id: 10, groupName: "Inactive Clients", remark: "Accounts with low or no recent activity", activeStatus: false },
  { id: 11, groupName: "North Region Dealers", remark: "Handles all northern area clients", activeStatus: true },
  { id: 12, groupName: "North Region Dealers", remark: "Handles one northern area clients", activeStatus: true },
 
];

export const FakeSubMainGroupData = [
  {
    id: 1,
    groupName: "North Region Dealers",
    subGroupName: "Delhi Division",
    remark: "Manages Delhi and NCR wholesale clients",
    activeStatus: true,
  },
  {
    id: 2,
    groupName: "South Zone Distributors",
    subGroupName: "Tamil Nadu Subgroup",
    remark: "Focus on Tamil Nadu state operations",
    activeStatus: true,
  },
  {
    id: 3,
    groupName: "Premium Clients",
    subGroupName: "Gold Tier",
    remark: "Top loyalty customers with >5 years association",
    activeStatus: false,
  },
  {
    id: 4,
    groupName: "Corporate Accounts",
    subGroupName: "Government Contracts",
    remark: "Public sector business clients",
    activeStatus: true,
  },
  {
    id: 5,
    groupName: "Retail Partners",
    subGroupName: "Franchise Stores",
    remark: "Small retail chains and outlets",
    activeStatus: false,
  },
  {
    id: 6,
    groupName: "International Clients",
    subGroupName: "Middle East",
    remark: "Serves clients in Dubai, UAE, and nearby countries",
    activeStatus: true,
  },
  {
    id: 7,
    groupName: "Online Vendors",
    subGroupName: "Marketplace Sellers",
    remark: "Sellers from Amazon and Flipkart",
    activeStatus: false,
  },
  {
    id: 8,
    groupName: "Seasonal Buyers",
    subGroupName: "Festive Clients",
    remark: "Clients active only during festive sales",
    activeStatus: true,
  },
  {
    id: 9,
    groupName: "Testing Group",
    subGroupName: "Internal QA",
    remark: "Used for test data and dummy transactions",
    activeStatus: true,
  },
  {
    id: 10,
    groupName: "Inactive Clients",
    subGroupName: "Dormant Users",
    remark: "Accounts not active for over a year",
    activeStatus: false,
  },
];



export const FakeProductTypeData = [
  {
    id: 1,
    typeName: "Electronics",
    remark: "Includes mobile phones, laptops, and accessories",
    isActive: true,
  },
  {
    id: 2,
    typeName: "Furniture",
    remark: "All types of home and office furniture",
    isActive: true,
  },
  {
    id: 3,
    typeName: "Clothing",
    remark: "Men’s and women’s apparel and accessories",
    isActive: false,
  },
  {
    id: 4,
    typeName: "Stationery",
    remark: "Office and school supplies",
    isActive: true,
  },
  {
    id: 5,
    typeName: "Groceries",
    remark: "Daily essentials and packaged food items",
    isActive: false,
  },
];

export const fakeAssemblyTypeData = [
  {
    id: 1,
    assemblyTypeName: "Electrical Assembly",
    remark: "Used for electrical components and circuits",
    active: true,
  },
  {
    id: 2,
    assemblyTypeName: "Mechanical Assembly",
    remark: "Includes metal and structural assemblies",
    active: false,
  },
  {
    id: 3,
    assemblyTypeName: "Plastic Assembly",
    remark: "Used for molded plastic parts",
    active: true,
  },
  {
    id: 4,
    assemblyTypeName: "Packaging Assembly",
    remark: "For packaging and shipping materials",
    active: true,
  },
];


// 📁 components/FakeData.js (add this section)
export const fakeUnitMasterData = [
  {
    id: 1,
    uomName: "Kilogram",
    remarks: "Used for measuring weight",
    active: true,
  },
  {
    id: 2,
    uomName: "Litre",
    remarks: "Used for measuring volume",
    active: true,
  },
  {
    id: 3,
    uomName: "Piece",
    remarks: "Used for counting items",
    active: false,
  },
  {
    id: 4,
    uomName: "Meter",
    remarks: "Used for measuring length",
    active: true,
  },
];



export const fakeItemMaterialData = [
  {
    id: 1,
    itemCode: "ITM-1001",
    itemName: "Electric Motor",
    unit: "PCS",
    quantity: 10,
    material: "Copper Wire",
    materialQuantity: 25, // kg
    materialRate: 760,
    materialAmount: 25 * 760,
  },
  {
    id: 2,
    itemCode: "ITM-1002",
    itemName: "Steel Frame",
    unit: "PCS",
    quantity: 5,
    material: "Mild Steel Sheet",
    materialQuantity: 40, // kg
    materialRate: 55,
    materialAmount: 40 * 55,
  },
  {
    id: 3,
    itemCode: "ITM-1003",
    itemName: "Control Panel",
    unit: "SET",
    quantity: 3,
    material: "Electronic Components",
    materialQuantity: 12, // packets
    materialRate: 210,
    materialAmount: 12 * 210,
  },
  {
    id: 4,
    itemCode: "ITM-1004",
    itemName: "Hydraulic Pump",
    unit: "PCS",
    quantity: 7,
    material: "Hydraulic Oil",
    materialQuantity: 18, // liters
    materialRate: 120,
    materialAmount: 18 * 120,
  },
  {
    id: 5,
    itemCode: "ITM-1005",
    itemName: "Gear Assembly",
    unit: "PCS",
    quantity: 15,
    material: "Alloy Steel Rod",
    materialQuantity: 30, // kg
    materialRate: 95,
    materialAmount: 30 * 95,
  },
];

export const fakeDepartments = ["HR", "IT", "Sales", "Production"];
export const fakeUserRoles = ["Admin", "Manager", "Executive", "Viewer"];
export const fakeStatuses = ["Active", "Inactive"];


export const FakeUserData = [
  {
    id: 1,
    fullName: "Rohit Sharma",
    email: "rohit.sharma@example.com",
    phone: "9876543210",
    department: "Sales",
    userRole: "Manager",
    status: "Active",
    username: "rohit_s",
    expiryDate: "2025-12-31"
  },
  {
    id: 2,
    fullName: "Priya Verma",
    email: "priya.verma@example.com",
    phone: "9988776655",
    department: "Marketing",
    userRole: "Executive",
    status: "Inactive",
    username: "priya_v",
    expiryDate: "2025-11-15"
  },
  {
    id: 3,
    fullName: "Aman Gupta",
    email: "aman.gupta@example.com",
    phone: "9090909090",
    department: "HR",
    userRole: "HR Assistant",
    status: "Active",
    username: "aman_g",
    expiryDate: "2026-01-20"
  },
  {
    id: 4,
    fullName: "Sneha Pandey",
    email: "sneha.pandey@example.com",
    phone: "9123456789",
    department: "Finance",
    userRole: "Accountant",
    status: "Active",
    username: "sneha_p",
    expiryDate: "2025-10-01"
  },
  {
    id: 5,
    fullName: "Vikas Singh",
    email: "vikas.singh@example.com",
    phone: "9812345678",
    department: "IT",
    userRole: "Developer",
    status: "Inactive",
    username: "vikas_dev",
    expiryDate: "2025-09-30"
  },
  {
    id: 6,
    fullName: "Nisha Rao",
    email: "nisha.rao@example.com",
    phone: "8800112233",
    department: "Admin",
    userRole: "Admin Executive",
    status: "Active",
    username: "nisha_r",
    expiryDate: "2026-02-11"
  },
  {
    id: 7,
    fullName: "Ajay Mehta",
    email: "ajay.mehta@example.com",
    phone: "7700998877",
    department: "Support",
    userRole: "Support Agent",
    status: "Active",
    username: "ajay_m",
    expiryDate: "2025-08-19"
  },
  {
    id: 8,
    fullName: "Kritika Sharma",
    email: "kritika.sharma@example.com",
    phone: "9001122334",
    department: "Sales",
    userRole: "Sales Executive",
    status: "Inactive",
    username: "kritika_s",
    expiryDate: "2026-05-05"
  },
  {
    id: 9,
    fullName: "Harsh Patel",
    email: "harsh.patel@example.com",
    phone: "9856231470",
    department: "IT",
    userRole: "Designer",
    status: "Active",
    username: "harsh_design",
    expiryDate: "2026-03-15"
  },
  {
    id: 10,
    fullName: "Simran Kaur",
    email: "simran.kaur@example.com",
    phone: "9998877665",
    department: "HR",
    userRole: "Recruiter",
    status: "Active",
    username: "simran_hr",
    expiryDate: "2025-07-22"
  }
];


export const fakeConsumableMaterialList = [
  {
    id: 1,
    name: "Cutting Oil",
    code: "CO-101",
    unit: "Ltr",
  },
  {
    id: 2,
    name: "Welding Rod",
    code: "WR-205",
    unit: "Kg",
  },
  {
    id: 3,
    name: "Grease",
    code: "GR-309",
    unit: "Kg",
  },
  {
    id: 4,
    name: "Coolant",
    code: "CL-412",
    unit: "Ltr",
  },
  {
    id: 5,
    name: "Thread Locker",
    code: "TL-518",
    unit: "Bottle",
  },
  {
    id: 6,
    name: "Cleaning Solvent",
    code: "CS-622",
    unit: "Ltr",
  },
  {
    id: 7,
    name: "Sand Paper",
    code: "SP-733",
    unit: "Pack",
  },
  {
    id: 8,
    name: "Lubricant Spray",
    code: "LS-847",
    unit: "Can",
  },
  {
    id: 9,
    name: "Anti-Rust Oil",
    code: "AR-950",
    unit: "Ltr",
  },
  {
    id: 10,
    name: "Cotton Waste",
    code: "CW-1040",
    unit: "Kg",
  },
];



export const fakeMaterialList = [
  {
    id: 1,
    productName: "Steel Cabinet",
    productCode: "SC-001",

    consumable: [
      { itemName: "Screw", code: "ITM-01", quantity: 20, rate: 2, unit: "pcs" },
      { itemName: "Glue", code: "ITM-02", quantity: 1, rate: 50, unit: "bottle" },
    ],

    manufacturing: [
      { itemName: "Steel Sheet", code: "MAT-10", quantity: 1, rate: 500, unit: "kg" },
      { itemName: "Handle", code: "MAT-11", quantity: 2, rate: 30, unit: "pcs" },
    ],

    status: "Active",
    isNew: true
  },

  {
    id: 2,
    productName: "Wooden Table",
    productCode: "WT-002",

    consumable: [
      { itemName: "Nails", code: "ITM-10", quantity: 50, rate: 1, unit: "pcs" },
      { itemName: "Fevicol", code: "ITM-11", quantity: 1, rate: 40, unit: "bottle" },
    ],

    manufacturing: [
      { itemName: "Wood Board", code: "MAT-20", quantity: 2, rate: 300, unit: "sqm" },
      { itemName: "Leg Frame", code: "MAT-21", quantity: 4, rate: 150, unit: "pcs" },
    ],

    status: "Inactive",
    isNew: false
  },
];





export const fakeInvoices = [
  {
    id: 1,
    invoice: {
      invNo: "INV-001",
      invDate: "2025-01-05",
      dueDays: 10,
      dueDate: "2025-01-15",
      customerName: "Rohan Sharma",
      mobile: "9876543210",
      address: "Delhi, India",
    },
    products: [
      {
        code: "P001",
        name: "Laptop",
        qty: 1,
        rate: 50000,
        sgst: 9,
        cgst: 9,
        igst: 0,
        discountPct: 5,
        discountAmt: 0,
      },
      {
        code: "P002",
        name: "Mouse",
        qty: 2,
        rate: 500,
        sgst: 9,
        cgst: 9,
        igst: 0,
        discountPct: 0,
        discountAmt: 50,
      },
      {
        code: "P003",
        name: "Keyboard",
        qty: 1,
        rate: 1200,
        sgst: 9,
        cgst: 9,
        igst: 0,
        discountPct: 0,
        discountAmt: 0,
      },
    ],
  },

  {
    id: 2,
    invoice: {
      invNo: "INV-002",
      invDate: "2025-01-07",
      dueDays: 7,
      dueDate: "2025-01-14",
      customerName: "Anita Verma",
      mobile: "9988776655",
      address: "Mumbai, India",
    },
    products: [
      {
        code: "P001",
        name: "Laptop",
        qty: 2,
        rate: 48000,
        sgst: 9,
        cgst: 9,
        igst: 0,
        discountPct: 3,
        discountAmt: 0,
      },
      {
        code: "P002",
        name: "Mouse",
        qty: 1,
        rate: 500,
        sgst: 9,
        cgst: 9,
        igst: 0,
        discountPct: 0,
        discountAmt: 0,
      },
      {
        code: "P003",
        name: "Keyboard",
        qty: 1,
        rate: 1100,
        sgst: 9,
        cgst: 9,
        igst: 0,
        discountPct: 0,
        discountAmt: 0,
      },
    ],
  },

  {
    id: 3,
    invoice: {
      invNo: "INV-003",
      invDate: "2025-01-10",
      dueDays: 15,
      dueDate: "2025-01-25",
      customerName: "Suresh Patel",
      mobile: "9123456789",
      address: "Ahmedabad, India",
    },
    products: [
      {
        code: "P001",
        name: "Laptop",
        qty: 1,
        rate: 52000,
        sgst: 9,
        cgst: 9,
        igst: 0,
        discountPct: 0,
        discountAmt: 2000,
      },
      {
        code: "P002",
        name: "Mouse",
        qty: 3,
        rate: 450,
        sgst: 9,
        cgst: 9,
        igst: 0,
        discountPct: 0,
        discountAmt: 0,
      },
      {
        code: "P003",
        name: "Keyboard",
        qty: 1,
        rate: 1250,
        sgst: 9,
        cgst: 9,
        igst: 0,
        discountPct: 0,
        discountAmt: 0,
      },
    ],
  },

  {
    id: 4,
    invoice: {
      invNo: "INV-004",
      invDate: "2025-01-12",
      dueDays: 5,
      dueDate: "2025-01-17",
      customerName: "Neha Gupta",
      mobile: "9012345678",
      address: "Jaipur, India",
    },
    products: [
      {
        code: "P001",
        name: "Laptop",
        qty: 1,
        rate: 49000,
        sgst: 9,
        cgst: 9,
        igst: 0,
        discountPct: 2,
        discountAmt: 0,
      },
      {
        code: "P002",
        name: "Mouse",
        qty: 2,
        rate: 520,
        sgst: 9,
        cgst: 9,
        igst: 0,
        discountPct: 0,
        discountAmt: 0,
      },
      {
        code: "P003",
        name: "Keyboard",
        qty: 2,
        rate: 1150,
        sgst: 9,
        cgst: 9,
        igst: 0,
        discountPct: 0,
        discountAmt: 0,
      },
    ],
  },

  {
    id: 5,
    invoice: {
      invNo: "INV-005",
      invDate: "2025-01-15",
      dueDays: 12,
      dueDate: "2025-01-27",
      customerName: "Amit Singh",
      mobile: "8899776655",
      address: "Lucknow, India",
    },
    products: [
      {
        code: "P001",
        name: "Laptop",
        qty: 1,
        rate: 51000,
        sgst: 9,
        cgst: 9,
        igst: 0,
        discountPct: 0,
        discountAmt: 1000,
      },
      {
        code: "P002",
        name: "Mouse",
        qty: 1,
        rate: 500,
        sgst: 9,
        cgst: 9,
        igst: 0,
        discountPct: 0,
        discountAmt: 0,
      },
      {
        code: "P003",
        name: "Keyboard",
        qty: 1,
        rate: 1200,
        sgst: 9,
        cgst: 9,
        igst: 0,
        discountPct: 0,
        discountAmt: 0,
      },
    ],
  },
];


export const fakePurchaseOrder = [
  {
    id: 1,
    invoice: {
      poNo: "PO-001",
      poDate: "2025-01-05",
      expectedDate: "2025-01-15",
      paymentTerms: "10 Days",
      supplierName: "Rohan Traders",
      gstNo: "07ABCDE1234F1Z5",
      deliveryLocation: "Delhi, India",
      status: "open",
    },
    products: [
      {
        itemCode: "P001",
        description: "Laptop",
        qty: 1,
        rate: 50000,
      },
      {
        itemCode: "P002",
        description: "Mouse",
        qty: 2,
        rate: 500,
      },
    ],
  },

  {
    id: 2,
    invoice: {
      poNo: "PO-002",
      poDate: "2025-01-07",
      expectedDate: "2025-01-14",
      paymentTerms: "7 Days",
      supplierName: "Anita Supplies",
      gstNo: "27ABCDE1234F1Z2",
      deliveryLocation: "Mumbai, India",
      status: "inprocess",
    },
    products: [
      {
        itemCode: "P001",
        description: "Laptop",
        qty: 2,
        rate: 48000,
      },
      {
        itemCode: "P002",
        description: "Mouse",
        qty: 1,
        rate: 500,
      },
    ],
  },

  {
    id: 3,
    invoice: {
      poNo: "PO-003",
      poDate: "2025-01-10",
      expectedDate: "2025-01-25",
      paymentTerms: "15 Days",
      supplierName: "Suresh Enterprises",
      gstNo: "24ABCDE1234F1Z9",
      deliveryLocation: "Ahmedabad, India",
      status: "open",
    },
    products: [
      {
        itemCode: "P001",
        description: "Laptop",
        qty: 1,
        rate: 52000,
      },
      {
        itemCode: "P002",
        description: "Mouse",
        qty: 3,
        rate: 450,
      },
    ],
  },

  {
    id: 4,
    invoice: {
      poNo: "PO-004",
      poDate: "2025-01-12",
      expectedDate: "2025-01-17",
      paymentTerms: "5 Days",
      supplierName: "Neha Distributors",
      gstNo: "08ABCDE1234F1Z3",
      deliveryLocation: "Jaipur, India",
      status: "fail",
    },
    products: [
      {
        itemCode: "P001",
        description: "Laptop",
        qty: 1,
        rate: 49000,
      },
    ],
  },

  {
    id: 5,
    invoice: {
      poNo: "PO-005",
      poDate: "2025-01-15",
      expectedDate: "2025-01-27",
      paymentTerms: "12 Days",
      supplierName: "Amit Tech Solutions",
      gstNo: "09ABCDE1234F1Z7",
      deliveryLocation: "Lucknow, India",
      status: "open",
    },
    products: [
      {
        itemCode: "P001",
        description: "Laptop",
        qty: 1,
        rate: 51000,
      },
    ],
  },
];


export const fakePurchaseGrn = [
  {
    id: 1,
    invoice: {
      grnNo: "GRN-001",
      vehicleNo: "DL01AB1234",
      poNo: "PO-001",
      receivedBy: "Rajan Dubey",
      supplier: "Rohan Traders",
      date: "2025-01-05",
      status: "open",
    },
    products: [
      {
        item: "Laptop",
        poQty: 1,
        receivedDate: "2025-01-06",
        accepted: true,
        rejected: false,
      },
      {
        item: "Mouse",
        poQty: 2,
        receivedDate: "2025-01-06",
        accepted: true,
        rejected: false,
      },
    ],
  },

  {
    id: 2,
    invoice: {
      grnNo: "GRN-002",
      vehicleNo: "MH02XY5678",
      poNo: "PO-002",
      receivedBy: "Anita Sharma",
      supplier: "Anita Supplies",
      date: "2025-01-07",
      status: "inprocess",
    },
    products: [
      {
        item: "Laptop",
        poQty: 2,
        receivedDate: "2025-01-08",
        accepted: true,
        rejected: false,
      },
      {
        item: "Mouse",
        poQty: 1,
        receivedDate: "2025-01-08",
        accepted: true,
        rejected: false,
      },
    ],
  },

  {
    id: 3,
    invoice: {
      grnNo: "GRN-003",
      vehicleNo: "GJ05CD4321",
      poNo: "PO-003",
      receivedBy: "Suresh Kumar",
      supplier: "Suresh Enterprises",
      date: "2025-01-10",
      status: "open",
    },
    products: [
      {
        item: "Laptop",
        poQty: 1,
        receivedDate: "2025-01-11",
        accepted: true,
        rejected: false,
      },
      {
        item: "Mouse",
        poQty: 3,
        receivedDate: "2025-01-11",
        accepted: true,
        rejected: false,
      },
    ],
  },

  {
    id: 4,
    invoice: {
      grnNo: "GRN-004",
      vehicleNo: "RJ14EF8765",
      poNo: "PO-004",
      receivedBy: "Neha Sharma",
      supplier: "Neha Distributors",
      date: "2025-01-12",
      status: "fail",
    },
    products: [
      {
        item: "Laptop",
        poQty: 1,
        receivedDate: "2025-01-13",
        accepted: false,
        rejected: true,
      },
    ],
  },

  {
    id: 5,
    invoice: {
      grnNo: "GRN-005",
      vehicleNo: "UP32GH9876",
      poNo: "PO-005",
      receivedBy: "Amit Singh",
      supplier: "Amit Tech Solutions",
      date: "2025-01-15",
      status: "open",
    },
    products: [
      {
        item: "Laptop",
        poQty: 1,
        receivedDate: "2025-01-16",
        accepted: true,
        rejected: false,
      },
    ],
  },
];


export const fakePurchaseInvoice = [
  {
    id: 1,
    invoice: {
      invoiceNo: "INV-001",
      poNo: "PO-001",
      supplier: "Rohan Traders",
      grnNo: "GRN-001",
      gstNo: "07AAECR2976F1Z5",
      date: "2025-01-05",
    },
    products: [
      {
        item: "Laptop",
        qty: 1,
        rate: 50000,
        gstPercent: 18,
        total: 59000, // 50000 + 18%
      },
      {
        item: "Mouse",
        qty: 2,
        rate: 500,
        gstPercent: 18,
        total: 1180,
      },
    ],
  },

  {
    id: 2,
    invoice: {
      invoiceNo: "INV-002",
      poNo: "PO-002",
      supplier: "Anita Supplies",
      grnNo: "GRN-002",
      gstNo: "27BBBCD1234Q1Z9",
      date: "2025-01-07",
    },
    products: [
      {
        item: "Laptop",
        qty: 2,
        rate: 48000,
        gstPercent: 18,
        total: 113280,
      },
      {
        item: "Mouse",
        qty: 1,
        rate: 600,
        gstPercent: 18,
        total: 708,
      },
    ],
  },

  {
    id: 3,
    invoice: {
      invoiceNo: "INV-003",
      poNo: "PO-003",
      supplier: "Suresh Enterprises",
      grnNo: "GRN-003",
      gstNo: "24CCDDE4567L1Z2",
      date: "2025-01-10",
    },
    products: [
      {
        item: "Laptop",
        qty: 1,
        rate: 52000,
        gstPercent: 18,
        total: 61360,
      },
      {
        item: "Mouse",
        qty: 3,
        rate: 450,
        gstPercent: 18,
        total: 1593,
      },
    ],
  },

  {
    id: 4,
    invoice: {
      invoiceNo: "INV-004",
      poNo: "PO-004",
      supplier: "Neha Distributors",
      grnNo: "GRN-004",
      gstNo: "08EEEFF7890M1Z3",
      date: "2025-01-12",
    },
    products: [
      {
        item: "Laptop",
        qty: 1,
        rate: 47000,
        gstPercent: 18,
        total: 55460,
      },
    ],
  },

  {
    id: 5,
    invoice: {
      invoiceNo: "INV-005",
      poNo: "PO-005",
      supplier: "Amit Tech Solutions",
      grnNo: "GRN-005",
      gstNo: "09GGGHH1234P1Z8",
      date: "2025-01-15",
    },
    products: [
      {
        item: "Laptop",
        qty: 1,
        rate: 51000,
        gstPercent: 18,
        total: 60180,
      },
    ],
  },
];

export const fakePurchaseReturn = [
  {
    id: 1,
    invoice: {
      returnNo: "PR-001",
      invoiceNo: "INV-001",
      supplier: "Rohan Traders",
      date: "2025-01-20",
      reason: "Damaged items received",
    },
    products: [
      {
        item: "Laptop",
        returnQty: 1,
        rate: 50000,
        amount: 50000,
      },
      {
        item: "Mouse",
        returnQty: 1,
        rate: 500,
        amount: 500,
      },
    ],
  },

  {
    id: 2,
    invoice: {
      returnNo: "PR-002",
      invoiceNo: "INV-002",
      supplier: "Anita Supplies",
      date: "2025-01-22",
      reason: "Excess quantity supplied",
    },
    products: [
      {
        item: "Laptop",
        returnQty: 1,
        rate: 48000,
        amount: 48000,
      },
    ],
  },

  {
    id: 3,
    invoice: {
      returnNo: "PR-003",
      invoiceNo: "INV-003",
      supplier: "Suresh Enterprises",
      date: "2025-01-25",
      reason: "Quality issue",
    },
    products: [
      {
        item: "Mouse",
        returnQty: 2,
        rate: 450,
        amount: 900,
      },
    ],
  },

  {
    id: 4,
    invoice: {
      returnNo: "PR-004",
      invoiceNo: "INV-004",
      supplier: "Neha Distributors",
      date: "2025-01-27",
      reason: "Wrong item delivered",
    },
    products: [
      {
        item: "Laptop",
        returnQty: 1,
        rate: 47000,
        amount: 47000,
      },
    ],
  },

  {
    id: 5,
    invoice: {
      returnNo: "PR-005",
      invoiceNo: "INV-005",
      supplier: "Amit Tech Solutions",
      date: "2025-01-28",
      reason: "Damaged packaging",
    },
    products: [
      {
        item: "Laptop",
        returnQty: 1,
        rate: 51000,
        amount: 51000,
      },
    ],
  },
];






